# Generated by Django 4.1.6 on 2023-12-04 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_birth', models.DateField()),
                ('employee_gender', models.CharField(choices=[('P', 'P'), ('L', 'L')], max_length=2)),
                ('employee_address', models.TextField()),
                ('employee_phone', models.CharField(max_length=14)),
                ('employee_department', models.CharField(choices=[('Pengasuh', 'Pengasuh'), ('Logistik', 'Logistik')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('parent_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=200, null=True)),
                ('m_name', models.CharField(max_length=200, null=True)),
                ('f_phone', models.CharField(max_length=14, null=True)),
                ('m_phone', models.CharField(max_length=14, null=True)),
                ('parent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='nonconsumable',
            fields=[
                ('nocon_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nocon_name', models.CharField(max_length=100)),
                ('nocon_con', models.CharField(choices=[('Buruk', 'Buruk'), ('Baik', 'Baik')], max_length=5)),
                ('nocon_kind', models.CharField(choices=[('Furn', 'Furn'), ('Toy', 'Toy')], max_length=10)),
                ('resp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='consumable',
            fields=[
                ('con_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('con_name', models.CharField(max_length=100)),
                ('con_con', models.CharField(choices=[('Buruk', 'Buruk'), ('Baik', 'Baik')], max_length=5)),
                ('con_kind', models.CharField(choices=[('Food', 'Food'), ('Med', 'Med'), ('Util', 'Util')], max_length=10)),
                ('resp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee')),
            ],
        ),
        migrations.CreateModel(
            name='child',
            fields=[
                ('child_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=200)),
                ('child_gender', models.CharField(choices=[('P', 'P'), ('L', 'L')], max_length=2)),
                ('child_birth', models.DateField()),
                ('disease', models.TextField(null=True)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('in_con', models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=6)),
                ('care_taker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myFirstApp.parent')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
