# Generated by Django 4.1.6 on 2023-11-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='child',
            fields=[
                ('child_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('child_name', models.CharField(max_length=200)),
                ('child_gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=2)),
                ('child_birth', models.DateField()),
                ('disease', models.TextField(null=True)),
                ('in_time', models.TimeField()),
                ('out_time', models.TimeField()),
                ('parent', models.CharField(max_length=7)),
                ('care_taker', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_birth', models.DateField()),
                ('employee_address', models.TextField()),
                ('employee_phone', models.CharField(max_length=14)),
                ('employee_department', models.CharField(choices=[('CT', 'Care Taker'), ('LT', 'Logistics')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=100)),
                ('equipment_con', models.CharField(choices=[('b', 'Bad'), ('g', 'Good')], default='g', max_length=2)),
                ('resp', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='parent',
            fields=[
                ('parent_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=200, null=True)),
                ('m_name', models.CharField(max_length=200, null=True)),
                ('f_phone', models.CharField(max_length=14, null=True)),
                ('m_phone', models.CharField(max_length=14, null=True)),
                ('parent_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='supply',
            fields=[
                ('supply_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('supply_name', models.CharField(max_length=100)),
                ('supply_amt', models.CharField(max_length=1000)),
                ('resp', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='toy',
            fields=[
                ('toy_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('toy_name', models.CharField(max_length=100)),
                ('toy_con', models.CharField(choices=[('b', 'Bad'), ('g', 'Good')], default='g', max_length=2)),
                ('resp', models.CharField(max_length=7)),
            ],
        ),
    ]
