# Generated by Django 4.1.6 on 2023-12-14 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='care_taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myFirstApp.employee'),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myFirstApp.employee'),
        ),
        migrations.AlterField(
            model_name='nonconsumable',
            name='resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='myFirstApp.employee'),
        ),
    ]
