# Generated by Django 4.1.6 on 2023-11-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_remove_child_care_taker_remove_equipment_resp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='care_taker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee'),
        ),
        migrations.AddField(
            model_name='supply',
            name='resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee'),
        ),
        migrations.AddField(
            model_name='toy',
            name='resp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFirstApp.employee'),
        ),
    ]
