# Generated by Django 4.1.6 on 2023-12-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_alter_child_care_taker_alter_consumable_resp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumable',
            name='con_con',
        ),
        migrations.AddField(
            model_name='consumable',
            name='con_amt',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
