# Generated by Django 4.1.6 on 2023-11-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0003_child_care_taker_equipment_resp_supply_resp_toy_resp'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=2),
        ),
    ]
