# Generated by Django 4.1.6 on 2023-11-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_alter_child_options_alter_equipment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='in_con',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=4),
        ),
    ]
