# Generated by Django 4.1.6 on 2023-11-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0006_child_in_con'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(choices=[('Care Taker', 'Care Taker'), ('Logistics', 'Logistics')], max_length=12),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_con',
            field=models.CharField(choices=[('bad', 'Bad'), ('good', 'Good')], default='g', max_length=5),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_con',
            field=models.CharField(choices=[('bad', 'Bad'), ('good', 'Good')], default='g', max_length=5),
        ),
    ]
