# Generated by Django 4.1.6 on 2023-11-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_alter_employee_employee_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='child_gender',
            field=models.CharField(choices=[('P', 'P'), ('L', 'L')], max_length=2),
        ),
        migrations.AlterField(
            model_name='child',
            name='in_con',
            field=models.CharField(choices=[('Ya', 'Ya'), ('Tidak', 'Tidak')], max_length=6),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_department',
            field=models.CharField(choices=[('Pengasuh', 'Pengasuh'), ('Logistik', 'Logistik')], max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_gender',
            field=models.CharField(choices=[('P', 'P'), ('L', 'L')], max_length=2),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='equipment_con',
            field=models.CharField(choices=[('Buruk', 'Buruk'), ('Baik', 'Baik')], max_length=5),
        ),
        migrations.AlterField(
            model_name='toy',
            name='toy_con',
            field=models.CharField(choices=[('Buruk', 'Buruk'), ('Baik', 'Baik')], max_length=5),
        ),
    ]
