from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('inner/', views.inner, name='inner'),
    path('chdb/', views.regch, name='child DB'),
    path('children/', views.children, name="children"),
    path('employee/', views.employees, name='employee'),
    path("logistics/", views.logistics, name="logistics"),
    path("parent/", views.parents, name="parent"),
    path("add_child/", views.add_child, name="add_child"),
    path("add_parent/", views.add_parent, name="add_parent"),
    path("add_employee/", views.add_employee, name="add_employee"),
    path("add_con/", views.add_con, name="add_con"),
    path("add_nocon/", views.add_nocon, name="add_nocon"),
    path("editpr/<str:parent_id>", views.edit_pr, name="edit_pr"),
    path("editem/<str:em_id>", views.edit_em, name="edit_em"),
    path("editch/<str:ch_id>", views.edit_kid, name="edit_ch"),
    path("editcon/<str:con_id>", views.edit_con, name="edit_con"),
    path("editnocon/<str:nocon_id>", views.edit_nocon, name="edit_con"),
    path("attendance/<str:ch_id>", views.att_kid, name="attendance"),
    path("parentone/<str:ch_id>/", views.parent_1, name="parent_1"),
    path("push_add_con/", views.push_add_con, name="push_add_con"),
    path("push_add_nocon/", views.push_add_nocon, name="push_add_nocon"),
    path("push_add_employee/", views.push_add_employee, name ="push_add_employee"),
    path("push_add_kid/", views.push_add_kid, name ="push_add_kid"),
    path("push_add_parent/", views.push_add_parent, name ="push_add_parent"),
    path("deletech/<str:child_id>", views.deletech, name="deletech"),
    path("deletepr/<str:parent_id>", views.deletepr, name="deletepr"),
    path("deleteem/<str:em_id>", views.deleteem, name="deleteem"),
    path("deletecon/<str:con_id>", views.deletecon, name="deletecon"),
    path("deletenocon/<str:nocon_id>", views.deletenocon, name="deletenocon"),
    path("push_edit_pr/", views.push_edit_pr, name="push_edit_pr"),
    path("push_edit_em/", views.push_edit_em, name="push_edit_em"),
    path("push_edit_kid/", views.push_edit_kid, name="push_edit_kid"),
    path("push_edit_con/", views.push_edit_con, name="push_edit_con"),
    path("push_edit_nocon/", views.push_edit_nocon, name="push_edit_nocon"),
    path("push_att_kid/", views.push_att_kid, name="push_att_kid"),
    path("res_att/", views.res_att, name="res_att"),
]
