from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('inner/', views.inner, name='inner'),
    path('chdb/', views.regch, name='child DB'),
    path('children/', views.children, name="children"),
    path('employee/', views.employees, name='employee'),
    path("logistics/", views.logistics, name="logistics"),
    path("parent/", views.parents, name="parent"),
    path("add_child/", views.add_child, name="add_child"),
    path("add_parent/", views.add_parent, name="add_parent"),
    path("add_employee/", views.add_employee, name="add_employee"),
    path("add_item/", views.add_item, name="add_item"),
    path("add_supply/", views.add_supply, name="add_supply"),
    path("add_toy/", views.add_toy, name="add_toy"),
    path("editpr/<str:parent_id>", views.edit_pr, name="edit_pr"),
    path("editem/<str:em_id>", views.edit_em, name="edit_em"),
    path("editch/<str:ch_id>", views.edit_kid, name="edit_ch"),
    path("editeq/<str:eq_id>", views.edit_eq, name="edit_eq"),
    path("edittoy/<str:toy_id>", views.edit_toy, name="edit_toy"),
    path("editsupp/<str:supp_id>", views.edit_supp, name="edit_supp"),
    path("attendance/<str:ch_id>", views.att_kid, name="attendance"),
    path("parentone/<str:ch_id>/", views.parent_1, name="parent_1"),
    path("push_add_item/", views.push_add_item, name="push_add_item"),
    path("push_add_toy/", views.push_add_toy, name="push_add_toy"),
    path("push_add_supply/", views.push_add_supply, name="push_add_supply"),
    path("push_add_employee/", views.push_add_employee, name ="push_add_employee"),
    path("push_add_kid/", views.push_add_kid, name ="push_add_kid"),
    path("push_add_parent/", views.push_add_parent, name ="push_add_parent"),
    path("deletech/<str:child_id>", views.deletech, name="deletech"),
    path("deletepr/<str:parent_id>", views.deletepr, name="deletepr"),
    path("deleteem/<str:em_id>", views.deleteem, name="deleteem"),
    path("deleteeq/<str:eq_id>", views.deleteeq, name="deleteeq"),
    path("deletetoy/<str:toy_id>", views.deletetoy, name="deletetoy"),
    path("deletesupp/<str:supp_id>", views.deletesupp, name="deletesupp"),
    path("push_edit_pr/", views.push_edit_pr, name="push_edit_pr"),
    path("push_edit_em/", views.push_edit_em, name="push_edit_em"),
    path("push_edit_kid/", views.push_edit_kid, name="push_edit_kid"),
    path("push_edit_eq/", views.push_edit_eq, name="push_edit_eq"),
    path("push_edit_toy/", views.push_edit_toy, name="push_edit_toy"),
    path("push_edit_supp/", views.push_edit_supp, name="push_edit_supp"),
    path("push_att_kid/", views.push_att_kid, name="push_att_kid"),


]
